# _config.yml
title: My Jekyll Site
description: A simple Jekyll site
baseurl: ""  # leave as "" if the site is hosted at the root
url: "https://username.github.io"  # change to your GitHub Pages URL
theme: jekyll-theme-slate  # or any other theme you prefer
markdown: kramdown
plugins:
  - jekyll-feed
